import { library } from "@fortawesome/fontawesome-svg-core";
import { fab } from "@fortawesome/free-brands-svg-icons";
import {
  faSpinner,
  faBars,
  faCamera,
  faEye,
  faCheck,
  faQuoteLeft,
  faQuoteRight,
  faPhone,
  faEnvelope,
  faMapMarkerAlt,
  faBold,
  faItalic,
  faUnderline,
  faLink,
  faListUl,
  faListOl,
  faCode,
  faEyeSlash,
  faUser,
  faMapPin,
  faTimesCircle,
  faBookmark,
  faPencilAlt,
  faFileImage,
  faChevronDown,
  faTrash,
  faThumbtack
} from "@fortawesome/free-solid-svg-icons";

const fontAwesomeConfig = library.add(
  fab,
  faSpinner,
  faBars,
  faCheck,
  faEye,
  faCamera,
  faQuoteLeft,
  faQuoteRight,
  faPhone,
  faEnvelope,
  faMapMarkerAlt,
  faBold,
  faItalic,
  faUnderline,
  faLink,
  faListOl,
  faListUl,
  faCode,
  faEyeSlash,
  faUser,
  faMapPin,
  faTimesCircle,
  faBookmark,
  faPencilAlt,
  faFileImage,
  faChevronDown,
  faTrash,
  faThumbtack
);

export default fontAwesomeConfig;
